version: "2"
services:
  db:
    image: postgres
    restart: always
    container_name: db_app
    env_file:
      - .env
    volumes:
      - ./data/db/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ['CMD-SHELL','pg_isready'] 
      interval: 10s
      timeout: 5s
      retries: 5
  cache:
    image: redis:6.2-alpine
    container_name: redis_app
    command: redis-server --save 20 1 --loglevel warning
    ports: 
      - "6379:6379"
    volumes:
      - ./data/cache:/data
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: app
    container_name: app
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
        - ./app/:/app
    command:
      python manage.py runserver 0.0.0.0:8000